### ISSUE TITLE
pp 显示有问题？

### ISSUE THREAD

**Issue by Cyl18** [Monodesu/osucat#10]
![image](https://user-images.githubusercontent.com/14993992/108608283-f8ec7480-7400-11eb-9ad8-edce96d6577e.png)
![image](https://user-images.githubusercontent.com/14993992/108608360-70ba9f00-7401-11eb-805b-6940f729de5c.png)
![image](https://user-images.githubusercontent.com/14993992/108608366-757f5300-7401-11eb-95b6-15c44040cdf1.png)
https://osu.ppy.sh/scores/osu/3488110315

**Comment by timi137137** [comment]
是否多次重试皆如此？

**Comment by Cyl18** [comment]
当时我!pr执行了两次都是这样 我去试试再打一打能不能复现

**Comment by Cyl18** [comment]
![image](https://user-images.githubusercontent.com/14993992/108700988-59cf9600-7542-11eb-9025-6c36cbe8046e.png)
![image](https://user-images.githubusercontent.com/14993992/108701003-5e944a00-7542-11eb-83d1-1220cf853de2.png)

**Comment by Monodesu** [comment]
@Cyl18 你好，谢谢对猫猫的关注，猫猫目前使用的pp计算系统还没有更新，下一个版本会尝试修复

**Comment by Monodesu** [comment]
fixed.
